import { QualityReport } from "../types";

export function generateMarkdownReport(report: QualityReport): string {
    const authorName = process.env.AUTHOR_NAME || "Mohamed Al Hamdhy";
    const githubUser = process.env.GITHUB_USERNAME || "mohamedalhamdhy";

    const gradeEmoji: Record<string, string> = { A: "🟢", B: "🟡", C: "🟠", D: "🔴", F: "💀" };
    const sevEmoji: Record<string, string> = { critical: "🔴", warning: "🟡", info: "🔵", good: "🟢" };

    const lines: string[] = [];

    lines.push(`# 🔍 Code Quality Report: ${report.repoName}`);
    lines.push("");
    lines.push(`> Generated by [CODESYS](https://github.com/${githubUser}/codesys) on ${new Date(report.analyzedAt).toLocaleString()}`);
    lines.push("");
    lines.push("## 📊 Overall Score");
    lines.push("");
    lines.push(`| Metric | Score | Grade |`);
    lines.push(`|--------|-------|-------|`);
    lines.push(`| **Overall** | ${report.overallScore}/100 | ${gradeEmoji[report.overallGrade]} **${report.overallGrade}** |`);
    lines.push(`| Maintainability | ${report.maintainabilityScore}/100 | ${gradeEmoji[gradeFromScore(report.maintainabilityScore)]} |`);
    lines.push(`| Complexity | ${report.complexityScore}/100 | ${gradeEmoji[gradeFromScore(report.complexityScore)]} |`);
    lines.push(`| Duplication | ${report.duplicationScore}/100 | ${gradeEmoji[gradeFromScore(report.duplicationScore)]} |`);
    lines.push(`| Style & Standards | ${report.styleScore}/100 | ${gradeEmoji[gradeFromScore(report.styleScore)]} |`);
    lines.push("");
    lines.push("## 📈 Statistics");
    lines.push("");
    lines.push(`| Stat | Value |`);
    lines.push(`|------|-------|`);
    lines.push(`| Total Files Analyzed | ${report.totalFiles} |`);
    lines.push(`| Total Lines of Code | ${report.totalLines.toLocaleString()} |`);
    lines.push(`| Total Functions | ${report.totalFunctions} |`);
    lines.push(`| Total Classes | ${report.totalClasses} |`);
    lines.push(`| Total Issues | ${report.totalIssues} |`);
    lines.push(`| Critical Issues | 🔴 ${report.criticalIssues} |`);
    lines.push(`| Warning Issues | 🟡 ${report.warningIssues} |`);
    lines.push(`| Primary Language | ${report.language} |`);
    lines.push(`| Architecture | ${report.architecture.type} |`);
    lines.push("");
    lines.push("## 🏗️ Architecture");
    lines.push("");
    lines.push(`- **Type:** ${report.architecture.type}`);
    lines.push(`- **Layers:** ${report.architecture.layers.join(", ") || "N/A"}`);
    lines.push(`- **Tests:** ${report.architecture.hasTests ? "✅ Present" : "❌ Not found"}`);
    lines.push(`- **Linting:** ${report.architecture.hasLinting ? "✅ Configured" : "❌ Not configured"}`);
    lines.push(`- **TypeScript:** ${report.architecture.hasTypeChecking ? "✅ Yes" : "❌ No"}`);
    lines.push(`- **Docker:** ${report.architecture.hasDocker ? "✅ Yes" : "❌ No"}`);
    lines.push(`- **CI/CD:** ${report.architecture.hasCICD ? "✅ Yes" : "❌ No"}`);
    lines.push("");
    lines.push("## 🐛 Top Issues");
    lines.push("");
    for (const issue of report.topIssues.slice(0, 10)) {
        lines.push(`### ${sevEmoji[issue.severity]} ${issue.type}`);
        lines.push(`**File:** \`${issue.file}\`${issue.line ? ` (line ${issue.line})` : ""}`);
        lines.push(`**Description:** ${issue.description}`);
        lines.push(`**Suggestion:** ${issue.suggestion}`);
        lines.push("");
    }

    const worstFiles = report.files.slice(0, 10);
    if (worstFiles.length > 0) {
        lines.push("## 📁 Files Needing Attention");
        lines.push("");
        lines.push(`| File | Grade | Score | Complexity | Issues |`);
        lines.push(`|------|-------|-------|------------|--------|`);
        for (const f of worstFiles) {
            lines.push(`| \`${f.path}\` | ${gradeEmoji[f.grade]} ${f.grade} | ${f.score} | ${f.cyclomaticComplexity} | ${f.issues.length} |`);
        }
        lines.push("");
    }

    if (report.aiSuggestions.length > 0) {
        lines.push("## 🤖 AI-Powered Suggestions");
        lines.push("");
        for (const s of report.aiSuggestions) {
            lines.push(s);
        }
        lines.push("");
    }

    lines.push("## 💡 Recommendations");
    lines.push("");
    const recs = generateRecommendations(report);
    for (const r of recs) lines.push(`- ${r}`);
    lines.push("");

    if (report.dependencies.length > 0) {
        lines.push("## 📦 Dependencies");
        lines.push("");
        lines.push(`- **Production:** ${report.totalDeps}`);
        lines.push(`- **Development:** ${report.devDeps}`);
        lines.push(`- **Total:** ${report.dependencies.length}`);
        lines.push("");
    }

    lines.push("---");
    lines.push(`*Generated by [CODESYS](https://github.com/${githubUser}/codesys) — Code Quality Automation by ${authorName}*`);

    return lines.join("\n");
}

function gradeFromScore(score: number): string {
    if (score >= 90) return "A";
    if (score >= 80) return "B";
    if (score >= 70) return "C";
    if (score >= 55) return "D";
    return "F";
}

function generateRecommendations(report: QualityReport): string[] {
    const recs: string[] = [];

    if (report.criticalIssues > 0)
        recs.push(`Address the **${report.criticalIssues} critical issues** first — they have the highest impact on maintainability.`);
    if (!report.architecture.hasTests)
        recs.push("Add **unit and integration tests** — untested code accumulates hidden bugs over time.");
    if (!report.architecture.hasLinting)
        recs.push("Configure **ESLint / a linter** to automate style enforcement and catch bugs early.");
    if (!report.architecture.hasTypeChecking)
        recs.push("Consider migrating to **TypeScript** for compile-time type safety.");
    if (!report.architecture.hasCICD)
        recs.push("Set up a **CI/CD pipeline** (GitHub Actions) to automate quality checks on every PR.");
    if (report.complexityScore < 70)
        recs.push("Reduce **cyclomatic complexity** by extracting complex logic into smaller, named functions.");
    if (report.duplicationScore < 70)
        recs.push("Eliminate **code duplication** by creating shared utility functions or abstractions.");
    if (report.totalDeps > 50)
        recs.push(`You have ${report.totalDeps} production dependencies — audit for unused or heavy packages with \`npm-check\`.`);
    if (recs.length === 0)
        recs.push("Codebase looks healthy. Continue applying SOLID principles and maintaining test coverage.");

    return recs;
}